


disabled_rules:

- identifier_name
- line_length
- type_body_length
- function_body_length
- cyclomatic_complexity
- shorthand_operator
- large_tuple
- trailing_whitespace
- file_length

#- syntactic_sugar
#- empty_enum_arguments
#- unused_optional_binding
#- implicit_getter
#- redundant_string_enum_value
#- todo
- multiple_closures_with_trailing_closure
#- for_where
#- trailing_comma
#- opening_brace
#- control_statement
#- comma
#- colon
#- vertical_whitespace
#- statement_position
#- trailing_newline
#- returning_whitespace
#- closure_parameter_position
#- type_name
#- mark
#- unused_closure_parameter
#- trailing_semicolon
#- returning_whitespace
#- ignores_empty_lines
#- unneeded_break
#- ignores_comments
#- legacy_constructor
#- unneeded_break_in_switch
#- return_arrow_whitespace
#- class_delegate_protocol
#- weak_delegate
#- unused_enumerated
#- leading_whitespace
#- superfluous_disable_command


excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

line_length:
warning: 150
ignores_function_declarations: true
ignores_comments: true
ignores_interpolated_strings: true
ignores_urls: true



